#!/usr/bin/env python3
import html
import json
import re
from pathlib import Path

MIN_WORDS = 631
TARGET_IDS = {1098, 1099, *range(1101, 1114)}

EXTRA = {
(1098, 'en'): "One reason cooks disagree about deveining is that the practical effect changes with shrimp size and preparation. In a large butterflied prawn, the tract is easy to see and any sandy material is concentrated in a single bite, so removing it can noticeably improve the result. In tiny shrimp destined for a curry, soup, dumpling filling, or chopped salad, the tract is narrow and its contents are diluted across the dish. Farmed and wild shrimp can also differ in what is visible inside because diet and harvest conditions differ. None of those differences changes the basic anatomy. If you buy shrimp already peeled and deveined, a short dark remnant may occasionally remain where the tract broke during processing; it can be lifted out if it bothers you, but it is not evidence that the entire batch was mishandled.",
(1098, 'es'): "Una de las razones por las que existen opiniones distintas sobre desvenar es que el efecto práctico cambia mucho con el tamaño y la receta. En un gambón grande abierto en mariposa, el conducto se ve con claridad y cualquier resto arenoso queda concentrado en un solo bocado, por lo que retirarlo puede mejorar de forma evidente el resultado. En camarones pequeños destinados a curry, sopa, rellenos o ensaladas picadas, el intestino es mucho más fino y su contenido queda repartido. También puede variar lo visible entre animales de cultivo y salvajes por diferencias de alimentación y captura. Nada de eso modifica la anatomía básica. Si compras camarones ya pelados y desvenados, a veces queda un tramo oscuro porque el conducto se rompió durante el procesado; puedes retirarlo si te molesta, pero ese pequeño resto no demuestra que el lote entero se haya manipulado mal.",
(1099, 'en'): "The way the material behaves can provide context without turning the kitchen into a laboratory. Struvite tends to be crystalline and brittle rather than razor-sharp, and food agencies describe it as softer than glass. A few mineral crystals scattered through otherwise normal tuna fit that known defect better than a single irregular shard accompanied by package damage. Even so, uncertainty should favor reporting rather than chewing the object to test hardness. Keep the label, best-before information, and lot code because those details let the manufacturer trace the production run. If the company confirms struvite, the issue is largely cosmetic. If the material cannot be identified, preserving the evidence is more useful than discarding the fragment and trying to infer its origin from memory.",
(1099, 'es'): "El comportamiento del material aporta contexto sin convertir la cocina en un laboratorio. La estruvita suele ser cristalina y quebradiza y las agencias alimentarias la describen como más blanda que el vidrio. Varios cristales minerales pequeños repartidos en un atún de aspecto normal encajan mejor con este defecto conocido que una única esquirla irregular acompañada de daños en el envase. Aun así, si existe duda es preferible comunicar la incidencia en vez de morder el objeto para comprobar su dureza. Conserva etiqueta, fecha y código de lote, porque esos datos permiten al fabricante rastrear la producción. Si la empresa confirma que se trata de estruvita, el problema es principalmente visual. Si el fragmento no puede identificarse, guardar la evidencia resulta mucho más útil que tirarla y tratar después de reconstruir su origen de memoria.",
(1101, 'en'): "Fermentation stage also changes what the jar looks like from day to day. Early in a lacto-ferment, the brine may begin almost clear and then become milky as bacterial numbers rise; later, suspended material can settle and leave a clearer layer near the top. Temperature can accelerate or slow that sequence, so two jars started with the same recipe do not always look identical if they fermented in different parts of a kitchen. What should remain consistent is control of the important variables: a tested salt concentration, vegetables kept below the brine, a clean vessel, and the temperature range specified by the method. Those controls are more informative than trying to judge success from transparency alone, because perfectly clear liquid does not guarantee a safe process and a cloudy ferment is not automatically defective.",
(1101, 'es'): "La fase de fermentación también cambia el aspecto del tarro de un día a otro. Al principio, una salmuera láctica puede verse casi transparente y volverse lechosa conforme aumenta la población bacteriana; más adelante parte del material suspendido puede depositarse y dejar una zona superior algo más clara. La temperatura acelera o frena esa secuencia, de modo que dos tarros preparados con la misma receta no siempre se ven idénticos si estuvieron en lugares distintos de la cocina. Lo que sí debe mantenerse estable es el control de las variables importantes: concentración de sal contrastada, verduras bajo la salmuera, recipiente limpio y temperatura indicada por el método. Esos factores aportan mucha más información que la transparencia, porque un líquido perfectamente claro no garantiza un proceso correcto y un fermento turbio no está automáticamente defectuoso.",
(1102, 'en'): "The geometry of the vessel can influence how often a film returns. A wide crock exposes more liquid to air than a narrow jar, and bits of spice or cucumber floating at the surface create small oxygen-rich islands where yeasts can establish. Fermentation weights, a follower leaf, or another method recommended by the recipe can help keep solids submerged. If you remove a thin yeast film but leave several pieces floating, it may reappear quickly because the underlying condition has not changed. Repeated heavy growth also deserves more attention than one light film: it can consume acids at the surface and impair flavor. The goal is not to create a sterile ferment, which would defeat the process, but to favor the acid-producing community below the brine while limiting organisms that thrive at the air interface.",
(1102, 'es'): "La forma del recipiente influye en la facilidad con la que reaparece la película. Una vasija ancha expone más líquido al aire que un tarro estrecho y los trozos de especias o pepino que flotan crean pequeñas zonas ricas en oxígeno donde las levaduras pueden instalarse. Pesos de fermentación u otros sistemas recomendados por la receta ayudan a mantener los sólidos sumergidos. Si retiras una capa fina pero dejas varios fragmentos en la superficie, puede volver pronto porque la causa no ha cambiado. Un crecimiento abundante y repetido merece más atención que una película ligera, ya que puede consumir acidez en la zona superior y empeorar el sabor. El objetivo no es esterilizar el fermento, sino favorecer la comunidad acidificante bajo la salmuera y limitar los microorganismos que prosperan justo en contacto con el aire.",
(1103, 'en'): "Salt has another practical role beyond seasoning: it draws water from shredded cabbage by osmosis, helping create the brine that excludes air from the vegetable. That is why changing the salt amount casually can affect both texture and microbial succession. If the cabbage does not release enough liquid to stay submerged, follow the tested recipe rather than topping the jar with an improvised mixture. During fermentation, press down floating shreds with clean equipment and keep the weight positioned so the brine covers the cabbage. A thin yeast layer is easier to manage when the underlying kraut remains acidic, crisp, and submerged. If the surface repeatedly dries out or large sections sit above the liquid, the batch no longer resembles the controlled environment assumed by preservation guidance and deserves a more conservative assessment.",
(1103, 'es'): "La sal cumple otra función además de dar sabor: extrae agua de la col por ósmosis y ayuda a crear la salmuera que mantiene el vegetal alejado del aire. Por eso modificar la cantidad de sal sin criterio puede alterar tanto la textura como la sucesión de microorganismos. Si la col no libera suficiente líquido para permanecer sumergida, sigue la receta contrastada en lugar de rellenar el tarro con una mezcla improvisada. Durante la fermentación, hunde los fragmentos flotantes con utensilios limpios y coloca el peso de modo que la salmuera cubra la col. Una película fina de levadura resulta mucho más manejable cuando el chucrut de debajo sigue ácido, firme y sumergido. Si la superficie se seca repetidamente o grandes zonas quedan fuera del líquido, el lote deja de parecerse al entorno controlado que presuponen las guías de conservación y conviene valorarlo con más prudencia.",
(1104, 'en'): "How tightly kimchi is packed also changes the drama when the jar opens. Carbon dioxide can remain dissolved in cold liquid, collect in pockets between leaves, or accumulate in the headspace. Warming the jar slightly during serving or transport reduces gas solubility, so bubbles may suddenly appear even though the same kimchi looked quiet in the refrigerator. Pieces of cabbage can also rise as gas becomes trapped underneath them, which is why leaving appropriate headspace matters. None of these effects requires an exotic contaminant; they follow ordinary fermentation physics. The practical response is controlled storage rather than trying to eliminate every bubble. Keep the jar cold once it reaches the flavor you want, avoid overfilling, and open an active ferment carefully so pressure and brine can escape without spraying the kitchen.",
(1104, 'es'): "Lo apretado que esté el kimchi dentro del tarro también cambia lo espectacular que resulta al abrirlo. El dióxido de carbono puede permanecer disuelto en el líquido frío, quedar atrapado entre hojas o acumularse en el espacio superior. Si el recipiente se templa durante el transporte o al servir, disminuye la solubilidad del gas y pueden aparecer de golpe muchas burbujas aunque en la nevera pareciera tranquilo. Los trozos de col también pueden subir cuando se acumula gas debajo, por eso conviene dejar el espacio superior que indique la receta. Ninguno de estos efectos exige un contaminante extraño; responden a la física normal de la fermentación. La solución práctica es controlar la conservación: enfría el kimchi cuando alcance el sabor que buscas, no llenes el envase en exceso y abre un fermento activo con cuidado para liberar presión y salmuera sin salpicaduras.",
(1105, 'en'): "The position of the liquid can also help explain what happened. Classic hooch often sits on top after a starter has collapsed, but a thin liquid layer can form in the middle when a very wet starter separates before all fermentation activity has stopped. Either pattern can follow long intervals between feedings. By contrast, a starter that produces a watery layer only minutes after mixing may simply have a hydration or flour-absorption issue rather than true hooch. Keep notes on flour type, water ratio, room temperature, and time to peak for a few cycles. Those observations make maintenance much easier because they show whether the culture is consistently exhausting its food too early. Adjusting the feed ratio or refrigerating between bakes is more effective than repeatedly rescuing the starter after a dark liquid layer has already developed.",
(1105, 'es'): "La posición del líquido también ayuda a interpretar lo ocurrido. El hooch clásico suele quedar arriba después de que la masa madre sube y colapsa, pero en un cultivo muy hidratado puede aparecer una franja líquida intermedia mientras todavía existe actividad. Ambos patrones pueden surgir por intervalos demasiado largos entre refrescos. En cambio, si la separación acuosa aparece pocos minutos después de mezclar, quizá se trate de hidratación o absorción de la harina y no de hooch generado por fermentación. Durante varios ciclos anota tipo de harina, proporción de agua, temperatura y tiempo hasta el máximo. Esas observaciones muestran si el cultivo agota sistemáticamente su alimento antes de la siguiente toma. Ajustar la proporción del refresco o refrigerar entre horneados resulta más eficaz que tener que rescatar continuamente una masa madre después de que ya se ha formado una capa muy oscura.",
(1106, 'en'): "A useful adjustment is to think in ratios rather than only in hours. Feeding one part mature starter with several parts fresh flour and water gives the microbes a larger reserve than a small refreshment, so the culture takes longer to become sharply acidic again. That does not mean a bigger feed is always better: if the room is cool or you need the starter ready soon, an enormous feeding may delay the peak too much. Flour choice matters as well because whole-grain flours provide different nutrients and buffering capacity from refined flour and can make activity feel faster. Watching how long your own starter takes to double, peak, and begin falling lets you match the ratio to your schedule. The acetone-like phase then becomes a useful diagnostic signal that the previous interval was too long for those conditions.",
(1106, 'es'): "Un ajuste útil consiste en pensar en proporciones y no solo en horas. Alimentar una parte de masa madre madura con varias partes de harina y agua nuevas aporta una reserva mayor que un refresco pequeño y tarda más en volver a un estado muy ácido y hambriento. Eso no significa que cuanto mayor sea el refresco mejor: en una cocina fría o si necesitas usar el cultivo pronto, una alimentación enorme puede retrasar demasiado el máximo. La harina también influye, porque las integrales aportan nutrientes y capacidad tampón diferentes a las refinadas y pueden cambiar el ritmo aparente. Observar cuánto tarda tu masa madre en duplicar, alcanzar el pico y empezar a bajar permite adaptar la proporción al horario real. El olor parecido a acetona se convierte así en una señal práctica de que el intervalo anterior fue demasiado largo para esas condiciones.",
(1107, 'en'): "The bumps can also affect how an egg behaves mechanically even when the contents are normal. A small isolated calcium spot is mostly cosmetic, but a very irregular shell may have areas of uneven thickness around the deposit. Commercial grading systems therefore care about shell shape and soundness, not just whether the egg looks interesting. At home, rotate the egg under good light and check the entire surface for hairline cracks before refrigerating or cooking it. The raised mineral itself does not need to be scraped off, and aggressive scraping can damage the cuticle that helps protect the shell. If the shell remains intact, handle and cook the egg in the same way as another egg from the carton. The unusual texture tells you about shell formation in the hen, not about a contaminant that needs to be washed away.",
(1107, 'es'): "Los bultos también pueden cambiar la resistencia mecánica de la cáscara aunque el interior sea normal. Un pequeño punto aislado de calcio es sobre todo cosmético, pero una cáscara muy irregular puede presentar espesores desiguales alrededor de los depósitos. Por eso los sistemas comerciales de clasificación valoran forma e integridad y no solo el aspecto curioso. En casa, gira el huevo bajo buena luz y comprueba toda la superficie en busca de grietas finas antes de guardarlo o cocinarlo. No hace falta raspar el mineral elevado y un raspado fuerte puede dañar la cutícula protectora de la cáscara. Si permanece entera, manipula y cocina el huevo como cualquier otro de la caja. La textura extraña cuenta algo sobre cómo se formó la cáscara dentro de la gallina, no sobre un contaminante exterior que haya que eliminar.",
(1108, 'en'): "Tenderloin preparation also depends on the final dish. For skewers, quick stir-fries, or breaded strips, removing a thick tendon can keep the piece from curling and prevent one chewy cord from dominating a small portion. If the meat will be minced for meatballs, chopped for a filling, or shredded after slow cooking, the benefit is much smaller because the connective tissue is divided into short pieces. Chilling the tenderloin well before trimming can make the tendon easier to grip and keeps the meat firmer under the knife. Work on a clean board reserved for raw poultry and wash hands and tools afterward. The popular tendon-removal tricks are therefore culinary techniques, not sanitation procedures; the food-safety controls remain separation from ready-to-eat foods, refrigeration, and adequate cooking.",
(1108, 'es'): "La conveniencia de retirar el tendón depende también del plato. En brochetas, salteados rápidos o tiras empanadas, quitar un cordón grueso evita que la pieza se deforme y que una fibra correosa domine un bocado pequeño. Si la carne va a picarse para albóndigas, cortarse para un relleno o deshilacharse tras una cocción húmeda, la ventaja es mucho menor porque el tejido conectivo queda dividido en fragmentos cortos. Enfriar bien el solomillo antes de recortar facilita sujetar el tendón y mantiene la carne firme bajo el cuchillo. Trabaja sobre una tabla destinada a pollo crudo y lava manos y utensilios después. Los trucos para sacar el cordón son técnicas culinarias, no procedimientos de desinfección; la seguridad sigue dependiendo de separar el pollo de alimentos listos para comer, refrigerarlo y cocinarlo adecuadamente.",
(1109, 'en'): "Roast style also changes how surface oil affects flavor extraction. Very dark roasting makes the bean more brittle and porous, so it grinds differently from a dense light roast and gives hot water faster access to soluble compounds. A shiny dark bean can therefore taste intense or bitter because of roast chemistry even when the oil is fresh. Staling is a separate time-dependent process in which volatile aromas escape and oxygen changes lipids and other compounds. If you compare coffee at home, smell the whole beans before grinding and then the freshly ground coffee; stale beans often reveal their loss of aromatic complexity much more clearly after grinding than by appearance alone. Using a recent roast date and storing only the amount you can consume reasonably soon is a better freshness strategy than sorting beans according to whether they shine.",
(1109, 'es'): "El estilo de tueste también cambia cómo influye el aceite superficial durante la extracción. Un tueste muy oscuro deja el grano más frágil y poroso, por lo que se muele de forma distinta a uno claro y permite que el agua acceda antes a compuestos solubles. Un grano brillante puede saber intenso o amargo por la propia química del tueste aunque el aceite sea reciente. El envejecimiento es un proceso diferente, dependiente del tiempo, en el que escapan aromas y el oxígeno modifica lípidos y otros compuestos. Para comparar café en casa, huele los granos enteros y después el café recién molido; la pérdida de complejidad aromática suele hacerse mucho más evidente tras moler que mirando la superficie. Usar una fecha de tueste reciente y comprar una cantidad que puedas consumir en un plazo razonable es una estrategia de frescura mucho mejor que clasificar los granos según brillen o no.",
(1110, 'en'): "A simple side-by-side brew can demonstrate the role of water better than the appearance of one cup. Use the same tea, dose, temperature, and steeping time, but prepare one cup with your usual hard tap water and another with a softer filtered water. If the mineral level is the main driver, the hard-water cup will usually develop the stronger skin as both drinks cool. This comparison also explains why descaling a kettle does not necessarily eliminate the film: scale on the appliance and dissolved calcium in freshly added water are related but not identical things. The film is most visible when a cup sits undisturbed because the surface layer has time to organize and strengthen. Stirring breaks it into fragments, which can make the drink look more speckled even though no new material has appeared.",
(1110, 'es'): "Una comparación sencilla entre dos tazas demuestra el papel del agua mejor que observar una sola infusión. Usa el mismo té, cantidad, temperatura y tiempo, pero prepara una taza con tu agua dura habitual y otra con agua filtrada más blanda. Si los minerales son el factor principal, la taza de agua dura suele desarrollar una película más marcada al enfriarse. Esto también explica por qué descalcificar el hervidor no siempre elimina el fenómeno: la cal adherida al aparato y el calcio disuelto en el agua nueva están relacionados, pero no son exactamente lo mismo. La capa se ve mejor cuando la taza permanece quieta porque la interfaz tiene tiempo para organizarse y ganar resistencia. Al removerla se rompe en fragmentos y la bebida puede parecer más moteada aunque no haya aparecido ningún material nuevo.",
(1111, 'en'): "Bottled kombucha adds another normal source of odd-looking material. During a second fermentation, residual yeast can continue consuming sugar and form fine sediment while a small new cellulose membrane develops near the neck of the bottle. Fruit puree, ginger, herbs, or juice added for flavor can contribute their own fibers and particles, making the distinction from plain kombucha even less tidy. The label and recipe therefore matter: sediment expected from a live, fruit-flavored drink is not interpreted the same way as a dry fuzzy patch growing at the air surface. When opening a carbonated bottle, chill it well and release pressure gradually because agitation can lift sediment and make it appear as floating clumps. Once the bottle settles, normal yeast material often sinks again or remains as soft strings rather than forming a dry colony.",
(1111, 'es'): "La kombucha embotellada añade otra fuente normal de materiales extraños. Durante una segunda fermentación, la levadura residual puede seguir consumiendo azúcar y formar sedimento fino, mientras cerca del cuello aparece una pequeña película nueva de celulosa. Puré de fruta, jengibre, hierbas o zumo usados para aromatizar aportan además sus propias fibras y partículas, de modo que una kombucha saborizada resulta todavía menos uniforme que una simple. La etiqueta y la receta importan: el sedimento esperado de una bebida viva con fruta no se interpreta igual que una mancha seca y vellosa creciendo en contacto con el aire. Para abrir una botella carbonatada, enfríala bien y libera presión poco a poco, porque agitarla levanta el sedimento y puede convertirlo temporalmente en grumos flotantes. Al reposar, la levadura normal suele volver a caer o quedar como hilos blandos, no como una colonia seca.",
(1112, 'en'): "Preparation can take advantage of the direction of the fibers instead of fighting them. For a raw celery salad, slicing the stalk very thinly on a diagonal cuts the long bundles into short pieces while preserving crispness. For a smooth braise or sauce base, small crosswise dice do the same job and expose more surface to heat. If you want long batons for dipping, that is the situation where peeling a particularly fibrous outer stalk can make the biggest sensory difference because the strings otherwise remain nearly their full length. The leafy tops and pale inner stalks usually need little or no peeling and can add celery aroma without the same toughness. Choosing a cutting method based on the dish saves edible vegetable and often removes the need for the extra peeling step altogether.",
(1112, 'es'): "La preparación puede aprovechar la dirección de las fibras en vez de luchar contra ellas. Para una ensalada cruda, cortar la penca muy fina y en diagonal divide los haces largos en segmentos cortos sin perder el crujido. Para un sofrito, guiso o base de salsa, un dado pequeño transversal consigue lo mismo y además expone más superficie al calor. Si quieres bastones largos para mojar en una salsa, ahí sí puede notarse mucho pelar una penca exterior especialmente fibrosa, porque los cordones conservarían casi toda su longitud. Las hojas y las pencas claras del corazón suelen necesitar poco o ningún pelado y aportan aroma sin la misma dureza. Elegir el corte según el plato permite conservar más parte comestible y, muchas veces, evita por completo el paso adicional de retirar hilos uno a uno.",
(1113, 'en'): "Temperature can make crystals seem to appear and disappear without changing what they are. Sugar is generally more soluble in warmer syrup, so a bottle warmed gently may look clear after crystals dissolve and then form new crystals again if the concentration remains too high and the syrup cools undisturbed. Mineral niter behaves differently and may settle as fine haze even when sugar crystals have disappeared. This is why producers measure density with tools such as hydrometers or refractometers rather than judging a batch only by how clear it looks while hot. For a consumer, the distinction is simpler: hard transparent or amber crystals at the bottom fit sucrose crystallization, while fine gritty sediment fits sugar sand. Neither pattern resembles a fuzzy biological growth on the surface, which requires the storage response described separately.",
(1113, 'es'): "La temperatura puede hacer que los cristales parezcan aparecer y desaparecer sin cambiar lo que son. El azúcar suele disolverse mejor en sirope templado, de modo que una botella calentada suavemente puede aclararse y volver a formar cristales cuando se enfría si la concentración sigue siendo demasiado alta. El niter mineral se comporta de otra manera y puede quedar como una neblina fina aunque los cristales de azúcar ya no se vean. Por eso los productores miden la densidad con hidrómetros o refractómetros y no juzgan un lote solo por su transparencia mientras está caliente. Para el consumidor la diferencia es más sencilla: cristales duros transparentes o ámbar en el fondo encajan con sacarosa cristalizada, mientras que un sedimento fino y arenoso encaja con sugar sand. Ninguno de esos patrones se parece a un crecimiento biológico velloso en la superficie, que requiere una respuesta de conservación distinta."
}


def visible_text(content_html):
    text = re.sub(r'(?is)<(?:script|style)\\b[^>]*>.*?</(?:script|style)>', ' ', content_html)
    text = re.sub(r'<[^>]+>', ' ', text)
    text = html.unescape(text)
    return re.sub(r'\\s+', ' ', text).strip()


def word_count(text):
    return len(re.findall(r"\\b[^\\W_]+(?:['’\\-][^\\W_]+)*\\b", text, flags=re.UNICODE))


def insert_before_summary(content, paragraph):
    marker = '<p><strong>'
    pos = content.rfind(marker)
    addition = '<p>' + paragraph + '</p>'
    if pos == -1:
        return content + addition
    return content[:pos] + addition + content[pos:]


changed = []
for lang in ('es', 'en'):
    folder = Path('content/articles') / lang
    for path in sorted(folder.glob('*.json')):
        data = json.loads(path.read_text(encoding='utf-8'))
        num = data.get('article_number')
        if num not in TARGET_IDS:
            continue
        before = word_count(visible_text(str(data.get('content_html', ''))))
        if before >= MIN_WORDS:
            print(f'PASS_EXISTING {lang}-{num} words={before}')
            continue
        paragraph = EXTRA[(num, lang)]
        data['content_html'] = insert_before_summary(data['content_html'], paragraph)
        after = word_count(visible_text(data['content_html']))
        if after < MIN_WORDS:
            raise SystemExit(f'STILL_SHORT {lang}-{num}: {before} -> {after}')
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        changed.append(str(path))
        print(f'EXPANDED {lang}-{num} words={before}->{after}')

if not changed:
    print('NO_CHANGES')
else:
    print(f'CHANGED={len(changed)}')
    for item in changed:
        print(item)
